version: "3.9"
services:

  zookeeper.kafka.statefun.rd.mvillalobos:
    image: confluentinc/cp-zookeeper:5.4.1
    ports:
      - "2181:2181"
    container_name: zookeeper.kafka.statefun.rd.mvillalobos
    env_file:
      - envs/zookeeper.env

  broker.kafka.statefun.rd.mvillalobos:
    image: confluentinc/cp-kafka:5.4.1
    ports:
      - "9092:9092"
      - "29092:29092"
    container_name: broker.kafka.statefun.rd.mvillalobos
    depends_on:
      - zookeeper.kafka.statefun.rd.mvillalobos
    env_file:
      - envs/kafka.env

  master.statefun.rd.mvillalobos:
    image: apache/flink-statefun:3.2.0-java11
    expose:
      - "6123"
    ports:
      - "8082:8081"
      - "8090:8090"
      - "8091:8091"
    env_file:
      - envs/master-statefun.env
    volumes:
      - ./module.yaml:/opt/statefun/modules/remote/module.yaml

  worker.statefun.rd.mvillalobos:
    image: apache/flink-statefun:3.2.0-java11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - master.statefun.rd.mvillalobos
    links:
      - "master.statefun.rd.mvillalobos:master"
    env_file:
      - envs/worker-statefun.env
    volumes:
      - ./module.yaml:/opt/statefun/modules/remote/module.yaml

  java.statefun.rd.mvillalobos:
    build:
      context: ping-statefun-app
    image: rd.mvillalobos/statefun/ping:latest
    hostname: java.statefun.rd.mvillalobos
    env_file:
      - envs/ping.env
    ports:
      - "8080:8080"

  python.statefun.rd.mvillalobos:
    build:
      context: pong-statefun-app
    image: rd.mvillalobos/statefun/pong:latest
    hostname: python.statefun.rd.mvillalobos
    ports:
      - "8000:8000"
