# copy description from https://docs.spring.io/spring-boot/docs/2.7.3/reference/htmlsingle/#appendix.application-properties
# document env variable override for other users and devops
# try to use a flat structure so that it is easy to understand
# always document each configuration value, no exceptions.

# Application name.
spring.application.name: ping

# The name of the application as displayed in the info actuator endpoint.
info.app.name: ${spring.application.name}

# A description of this application for the info actuator endpoint.
info.app.description: Ping Stateful Function

# Controls how much git information to display in the actuator/info endpoint. Values are: simple or full
management.info.git.mode: simple

# Endpoint IDs that should be included or '*' for all.
management.endpoints.web.exposure.include: "*"

# When to show full health details.
management.endpoint.health.show-details: always

# Flag that indicates if springfox should scan services to produce specifications.
# Turn this to false in production to disable swagger.
springfox.documentation.enabled: true

# Comma-delimited list of host:port pairs to use for establishing the initial connections to the Kafka cluster. Applies to all components unless overridden.
# override with env variable SPRING_KAFKA_BOOTSTRAPSERVERS
spring.kafka.bootstrap-servers: localhost:9092

# spring.kafka.properties.*
# Additional properties, common to producers and consumers, used to configure the client.
spring.kafka.properties:
  # configures kafka security protocol. Valid values are PLAINTEXT or SSL.
  # override with env variable SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
  security.protocol: ${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:PLAINTEXT}

# Serializer class for keys.
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
# Serializer class for values.
spring.kafka.producer.value-serializer: mvillalobos.rd.statefun.ping.implementation.io.StateFunStringSerializer

# the ingress topic used to receive concept evaluation request.
# override with env variable MVILLALOBOS_RD_STATEFUN_PING_PINGREQUEST_STATEFUN_INGRESS_TOPIC
mvillalobos.rd.statefun.ping.ping-request.statefun.ingress.topic: ping-request